services:
  - type: web
    name: test-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

